# Permalinks
permalink:        date

# Setup
title:            'derhagen'
tagline:          'A blog I quickly set up to get writing'
description:      'A blog I quickly set up to get writing'
baseurl:          ""
paginate:         5

# About and contact
author:
  name:           'derhagen'
  photourl:       'https://avatars1.githubusercontent.com/u/2806328?s=460&u=8190bb7001f9ec5a15d1aa4a7715860392827a96&v=4'

# Gems
plugins:
  - jekyll-paginate
